name: stars_to_s3
on:
  # schedule:
  #   - cron: "45 */8 * * *"
  workflow_dispatch:

jobs:
  stars_to_s3:
    runs-on: ubuntu-latest
    environment: crons

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3
      - uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # pin@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: sync to s3
        run: |
          wget https://github.com/planetscale/cli/releases/download/v0.115.0/pscale_0.115.0_linux_amd64.deb
          sudo dpkg -i pscale_0.115.0_linux_amd64.deb
          python lib/crons/star_trends_to_s3.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PSCALE_TOKEN: ${{ secrets.PSCALE_TOKEN }}
          PSCALE_ID: ${{ secrets.PSCALE_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
